name: "Continuous Integration"

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: "always"
  RUST_BACKTRACE: "full"
  RUSTFLAGS: "-C opt-level=0 -g"
jobs:
  matrix:
    strategy:
      matrix:
        bin: [unregulated-artificial-intelligence, llm]
        os: [ubuntu-latest, macos-latest]
        toolchain:
          - stable
          - nightly

    name: "ZION, HEAR ME! ${{  matrix.bin }}@${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: run
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin ${{ matrix.bin }}
