name: "Continuous Integration"

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: "always"
  RUST_BACKTRACE: "full"
  RUSTFLAGS: "-C opt-level=0 -g"
jobs:
  matrix:
    strategy:
      matrix:
        bin: ["unregulated-artificial-intelligence", "llm", "deepseek", "openai"]
        os: [ubuntu-latest, macos-latest]

    name: "ZION, HEAR ME! ${{  matrix.bin }}@${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - name: run
        uses: actions-rs/cargo@v1
        with:
          command: run --bin ${{ matrix.bin }}
